# Generated by Django 4.2.7 on 2023-11-27 09:25

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "is_completed",
                    todo.models.CustomBooleanField(
                        choices=[(True, "Done"), (False, "Not Done")], default=False
                    ),
                ),
                ("tags", models.ManyToManyField(related_name="tasks", to="todo.tag")),
            ],
            options={
                "ordering": ["-is_completed", "-created_at"],
            },
        ),
    ]
